
on:
  push:
    paths:
    - 'contracts/**/*.sol'
    - '.github/workflows/*.yaml'
    - '.github/workflows/*.yml'

name: foundry tests

env:
  ETH_RPC_URL:  ${{ secrets.ETH_RPC_URL2 }} 

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile
        id: compile
        run: forge build --sizes

      - name: Run Gas Snapshot
        id: gas
        run: forge snapshot --allow-failure